version: "3.0"
services:
  stag-store-service:
    image: ${ECR_REGISTRY}/${IMAGE_NAME}:${TAG}
    ports:
      - 7200:7200
      - 7201:7201
    environment:
      - GRPC_PORT=7200
      - HTTP_PORT=7201
      - DB_HOST=staging-postgre
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_NAME=store-service
      - GRPC_UTILITY_HOST=stag-utility-service:7300
      - STORAGE_ENDPOINT=172.27.0.3:9000
      - STORAGE_PUBLIC_URL=http://172.19.14.120:9100
      - STORAGE_ACCESS_KEY=18qnD4xSmhYZPXbTOICR
      - STORAGE_SECRET_KEY=OYbMiwBEmTHayFtest5Y0V946FrTs3ZnDMpjV5lM
      - STORAGE_BUCKET_NAME=mitra-apps
      - JWT_SECRET=secret
    networks:
      - grpc_network
    volumes:
      - ./uom.json:/app/uom.json
networks:
  grpc_network:
    external: true