version: "3.0"
services:
  prod-store-service:
    image: ${ECR_REGISTRY}/${IMAGE_NAME}:${TAG}
    ports:
      - 9200:9200
      - 9201:9201
    environment:
      - GRPC_PORT=9200
      - HTTP_PORT=9201
      - DB_HOST=prod-postgre
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_NAME=store-service
      - GRPC_UTILITY_HOST=stag-utility-service:9300
      - JWT_SECRET=secret
    networks:
      - grpc_network
networks:
  grpc_network:
    external: true