version: "3.0"
services:
  store-service:
    image: ${ECR_REGISTRY}/${IMAGE_NAME}:${COMMIT_HASH}
    ports:
      - 9100:9100
      - 9101:9101
    environment:
      - GRPC_PORT=9100
      - HTTP_PORT=9101
      - DB_HOST=store-database
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_NAME=store-service
    depends_on:
      store-database:
        condition: service_healthy
    networks:
      - grpc_network
  store-database:
    image: postgres:14-alpine
    restart: always
    volumes:
      - ./ignoredmodule/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=store-service
    ports:
      - 5434:5432
    expose:
      - 5434
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - grpc_network
volumes:
  db:
    driver: local
networks:
  grpc_network:
    external: true