version: "3.0"
services:
  stag-store-service:
    image: ${ECR_REGISTRY}/${IMAGE_NAME}:${COMMIT_HASH}
    ports:
      - 7200:7200
      - 7201:7201
    environment:
      - GRPC_PORT=7200
      - HTTP_PORT=7201
      - DB_HOST=staging-postgre
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_NAME=store-service
      - STORAGE_ENDPOINT=127.0.0.1:9100
      - STORAGE_ACCESS_KEY=lRjNBUXZTV22HSqLRnQr
      - STORAGE_SECRET_KEY=HV5vwZ6D1DMC4pvRiloyWIDrv6wRTgJkNS1bBG1s
      - STORAGE_BUCKET_NAME=mitra-apps
      - JWT_SECRET=secret
    networks:
      - grpc_network
networks:
  grpc_network:
    external: true