version: "3.0"
services:
  stag-store-service:
    image: ${ECR_REGISTRY}/${IMAGE_NAME}:${COMMIT_HASH}
    ports:
      - 7200:7200
      - 7201:7201
    environment:
      - GRPC_PORT=7200
      - HTTP_PORT=7201
      - DB_HOST=staging-postgre
      - DB_PORT=5433
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_NAME=store-service
    networks:
      - grpc_network
networks:
  grpc_network:
    external: true