# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Pull Request Validation

on:
  pull_request:
    branches: [ "staging" ]

jobs:

  test:
    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'
      env:
        GOPRIVATE: "github.com/Mitra-Apps/*"

    - name: Install Dependencies
      run: |
        go get -v github.com/Mitra-Apps/be-utility-service@staging
        go get -v github.com/Mitra-Apps/be-user-service@development
        go mod tidy

    - name: Run Unit Test
      run: go test -v -coverprofile=coverage.out  ./service/

    - name: Show Coverage
      run: go tool cover -func=coverage.out | grep total | awk '{print $3}'

  check_coverage:
    name: Check Coverage Percentage
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Check coverage
      run: |
        threshold=60
        coverage=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
        if (( $(echo "$coverage < $threshold" | bc -l) )); then
          echo "Coverage is below the threshold of $threshold%"
          exit 1
        else
          echo "Coverage is acceptable ($coverage%)"
        fi
